from typing import Dict, Any

# Clinical LOINC Terminology Codes for NCD Screening (adapted from bezs-emr-gql)
LOINC_CODES: Dict[str, Dict[str, Any]] = {
    "SYSTOLIC_BP": {
        "code": "8480-6",
        "display": "Systolic blood pressure",
        "system": "http://loinc.org",
        "unit": "mmHg",
        "normal_max": 120.0,
    },
    "DIASTOLIC_BP": {
        "code": "8462-4",
        "display": "Diastolic blood pressure",
        "system": "http://loinc.org",
        "unit": "mmHg",
        "normal_max": 80.0,
    },
    "HEART_RATE": {
        "code": "8867-4",
        "display": "Heart rate",
        "system": "http://loinc.org",
        "unit": "beats/min",
        "normal_range": (60.0, 100.0),
    },
    "FASTING_GLUCOSE": {
        "code": "1558-6",
        "display": "Fasting glucose [Mass/volume] in Blood",
        "system": "http://loinc.org",
        "unit": "mg/dL",
        "normal_max": 99.0,
        "prediabetes_max": 125.0,
    },
    "HBA1C": {
        "code": "4548-4",
        "display": "Hemoglobin A1c/Hemoglobin.total in Blood",
        "system": "http://loinc.org",
        "unit": "%",
        "normal_max": 5.6,
        "prediabetes_max": 6.4,
    },
    "TOTAL_CHOLESTEROL": {
        "code": "2093-3",
        "display": "Cholesterol [Mass/volume] in Serum or Plasma",
        "system": "http://loinc.org",
        "unit": "mg/dL",
        "normal_max": 200.0,
    },
    "HDL_CHOLESTEROL": {
        "code": "2085-9",
        "display": "Cholesterol in HDL [Mass/volume] in Serum or Plasma",
        "system": "http://loinc.org",
        "unit": "mg/dL",
        "normal_min_male": 40.0,
        "normal_min_female": 50.0,
    },
    "TRIGLYCERIDES": {
        "code": "2571-8",
        "display": "Triglyceride [Mass/volume] in Serum or Plasma",
        "system": "http://loinc.org",
        "unit": "mg/dL",
        "normal_max": 150.0,
    },
    "BMI": {
        "code": "39156-5",
        "display": "Body mass index (BMI) [Ratio]",
        "system": "http://loinc.org",
        "unit": "kg/m2",
        "normal_max_asian_indian": 22.9,
        "overweight_cutoff_asian_indian": 23.0,
        "obese_cutoff_asian_indian": 25.0,
    },
    "WAIST_CIRCUMFERENCE": {
        "code": "8280-0",
        "display": "Waist Circumference at umbilicus by Tape measure",
        "system": "http://loinc.org",
        "unit": "cm",
        "cutoff_male_asian_indian": 90.0,
        "cutoff_female_asian_indian": 80.0,
    },
    "EGFR": {
        "code": "33914-3",
        "display": "Glomerular filtration rate/1.73 sq M.predicted",
        "system": "http://loinc.org",
        "unit": "mL/min/1.73m2",
        "normal_min": 90.0,
    },
    "HEIGHT": {
        "code": "8302-2",
        "display": "Body height",
        "system": "http://loinc.org",
        "unit": "cm",
    },
    "WEIGHT": {
        "code": "29463-7",
        "display": "Body weight",
        "system": "http://loinc.org",
        "unit": "kg",
    },
    "LDL_CHOLESTEROL": {
        "code": "13457-7",
        "display": "Cholesterol in LDL [Mass/volume] in Serum or Plasma",
        "system": "http://loinc.org",
        "unit": "mg/dL",
        "normal_max": 100.0,
    },
    "SERUM_CREATININE": {
        "code": "2160-0",
        "display": "Creatinine [Mass/volume] in Serum or Plasma",
        "system": "http://loinc.org",
        "unit": "mg/dL",
        "normal_max_male": 1.2,
        "normal_max_female": 1.0,
    },
    "PHYSICAL_ACTIVITY": {
        "code": "89555-7",
        "display": "Moderate to vigorous physical activity minutes per week",
        "system": "http://loinc.org",
        "unit": "min/week",
        "target_min": 150.0,
    },
    "SLEEP_HOURS": {
        "code": "93832-4",
        "display": "Sleep duration",
        "system": "http://loinc.org",
        "unit": "hours",
        "normal_min": 7.0,
    },
    "STRESS_LEVEL": {
        "code": "76542-0",
        "display": "Perceived stress scale score (0-10)",
        "system": "http://loinc.org",
        "unit": "score",
        "normal_max": 5.0,
    },
}

# SNOMED CT Clinical Findings
SNOMED_CODES: Dict[str, Dict[str, str]] = {
    "PREDIABETES": {"code": "714628002", "display": "Prediabetes (disorder)"},
    "DIABETES_TYPE_2": {"code": "44054006", "display": "Diabetes mellitus type 2 (disorder)"},
    "PREHYPERTENSION": {"code": "38341003", "display": "Prehypertension (finding)"},
    "ESSENTIAL_HYPERTENSION": {"code": "59621000", "display": "Essential hypertension (disorder)"},
    "METABOLIC_SYNDROME": {"code": "237602007", "display": "Metabolic syndrome X (disorder)"},
    "CARDIOVASCULAR_RISK": {"code": "429000007", "display": "Cardiovascular risk score (observable entity)"},
}
